### ISSUE TITLE
Configuration of docker doesn't exposes 8080 

### ISSUE THREAD

**Issue by tupizz** [saefullohmaslul/golang-example#4]
I'm trying to up the server with docker, but I guess that something was missing from configuration files. 

For example, when I run `make docker-dev` and after that I run to check all docker containers that are up I get the following output: 

![image](https://user-images.githubusercontent.com/15824865/81342137-14aca700-9089-11ea-8657-ca7059eba6e5.png)

The column PORTS of container golang-example_app its null, and if I acces my localhost on port 8080 I can't get a response from go server.

**Comment by saefullohmaslul** [comment]
@tupizz I change the execution from `make docker-dev` to `make run-local`. And I'm adding configuration to expose port [in here](https://github.com/saefullohmaslul/golang-example/commit/a16b3323985f8b306b99414ab699a8df0ba48263?diff=split)

You can see the latest change when I'm running, this ports was exposed

![Screenshot from 2020-05-09 13-06-50](https://user-images.githubusercontent.com/20754023/81465747-632b8400-91f6-11ea-81e6-f25952396903.png)

**Comment by tupizz** [comment]
very nice!
